version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    depends_on:
      mongodb:
        condition: service_healthy
        required: true
    environment:
      MONGODB_URL: mongodb://mongodb:27017/?replicaSet=rs0
      MONGODB_APP_DB_NAME: app_db
      TEST_DB_NAME: test_db

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
